### ISSUE TITLE
执行结果 output 为空

### ISSUE THREAD

**Issue by vmto** [sprayman1999/YourPhotoBorder#1]
命令：
python3 ./main.py -c ./configs/your_photo_border.json -f ./aa/ -o ./output/

输出信息：
Namespace(config='./configs/your_photo_border.json', file='./aa/', source_file=None, output='./output/', default_image_maker=None, enforce_config=None)
[*] All task is finished!

执行结果：
aa目录有两张照片，output为空。

有什么注意事项吗？

**Comment by sprayman1999** [comment]
哥们可以用用web版的，链接 -> https://github.com/sprayman1999/YourPhotoBorder-Web

**Comment by vmto** [comment]
Web版本可以，不过，默认配置的时候，这个路径：/static/assets/camera_logos/SONY/logo.jpg 里的SONY，应为Sony
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月26日(星期二) 上午10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sprayman1999/YourPhotoBorder] 执行结果 output 为空 (Issue #1)












https://github.com/sprayman1999/YourPhotoBorder-Web

**Comment by sprayman1999** [comment]
我今晚看看如何修复这些问题，感谢你的issue。时隔快一年，很惊讶你很快就回复我了，我确实没想到会有人去用这个代码，甚至还有改进意见 :)

**Comment by sprayman1999** [comment]
确认是因为apply_async导致的问题，因为它是用于多进程调用的函数，会导致有变动的全局变量无法同步到新进程，本次问题是config和args变量在apply_async调用时为空导致的，目前多进程代码修改为多线程，应该是没有问题了

review commit：https://github.com/sprayman1999/YourPhotoBorder/commit/ec4c94faabe5a702517cdcc35e3c9e63556fa602
